version: "3.4"
x-logging: &logging
  logging:
    driver: journald

services:
  consensus:
    restart: "${RESTART}"
    build:
      context: ./lighthouse
      dockerfile: ${LH_DOCKERFILE}
      args:
        - BUILD_TARGET=${LH_SRC_BUILD_TARGET}
        - DOCKER_TAG=${LH_DOCKER_TAG}
    image: lighthouse:local
    user: lhconsensus
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    stop_grace_period: 1m
    volumes:
      - lhconsensus-data:/var/lib/lighthouse
    ports:
      - ${LH_PORT}:${LH_PORT}/tcp
      - ${LH_PORT}:${LH_PORT}/udp
    expose:
      - 5052/tcp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - lighthouse
      - bn
      - --disable-upnp
      - --datadir
      - /var/lib/lighthouse
      - --http
      - --http-address
      - 0.0.0.0
      - --http-port
      - "5052"
      - --network
      - ${NETWORK}
      - --port
      - ${LH_PORT}
      - --target-peers
      - ${LH_PEER_COUNT}
      - --eth1-endpoints
      - ${EC_NODE}
      - --eth1-blocks-per-log-query
      - "150"
      - --debug-level=${LOG_LEVEL}
      - --staking
    command: ${LH_RAPID_SYNC}
    labels:
      - traefik.enable=true
      - traefik.http.routers.cc.entrypoints=websecure
      - traefik.http.routers.cc.rule=Host(`${CC_HOST}.${DOMAIN}`)
      - traefik.http.services.cc.loadbalancer.server.port=5052
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
volumes:
  lhconsensus-data:
